---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundrylondon/backup-and-restore}

inputs:
- name: version
- name: pcf-backup-and-restore
  path: src/github.com/pivotal-cf/pcf-backup-and-restore
- name: pcf-backup-and-restore-meta

params:
  TEAM_GPG_KEY:

outputs:
- name: pbr-build

run:
  path: src/github.com/pivotal-cf/pcf-backup-and-restore/ci/scripts/build.sh
